### ISSUE TITLE
Task Unclear

### ISSUE THREAD

**Issue by Felipe-Hub** [ironhack-labs/lab-sql-9#1]
@sandrabosk 

Last task is unclear, students couldn't figure out. Also, they are trying to get everything in one query with lots of joins (check if that is ok). Also, 'most rented film category by client' solution suggestion is not returning the desired result. Solved it with subqueries:
 
SELECT customer, category_name FROM
(SELECT rental.customer_id as customer, count(rental.rental_id) as total_rentals, film_category.category_id, category.name as category_name,
row_number() over (partition by rental.customer_id order by count(rental.rental_id) desc) as ranking_max_rented_category
FROM rental
INNER JOIN inventory ON rental.inventory_id = inventory.inventory_id
INNER JOIN film_category ON inventory.film_id = film_category.film_id
INNER JOIN category ON film_category.category_id = category.category_id
GROUP BY rental.customer_id, film_category.category_id, category.name) AS table_popular_category
WHERE ranking_max_rented_category = 1
ORDER BY customer;

**Comment by haggarw3** [comment]
Thanks for pointing it out Felipe. We have now changed the questions on the lab. Solution file will also be updated today or tomorrow.

**Comment by ironhack-edu** [comment]
Solution updated, changes merged. Thank you both, you rock 🚀🚀
